# Generated by Django 5.0.2 on 2024-02-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Devices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("client_name", models.CharField(max_length=100)),
                ("client_phone", models.CharField(max_length=30)),
                ("client_email", models.EmailField(max_length=254)),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Em Andamento", "Em Andamento"),
                            ("Aguardando Retirada", "Aguardando Retirada"),
                            ("Em Orçamento", "Em Orçamento"),
                        ],
                        max_length=50,
                    ),
                ),
                ("techinician", models.CharField(max_length=50)),
                ("problem_description", models.TextField()),
            ],
        ),
    ]
