# Generated by Django 5.0.2 on 2024-02-21 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devices",
            old_name="techinician",
            new_name="technician",
        ),
    ]
