# Generated by Django 5.0.2 on 2024-02-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_techinician_devices_technician'),
        ('technicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('Aguardando Aprovação', 'Aguardando Aprovação'), ('Em Andamento', 'Em Andamento'), ('Aguardando Retirada', 'Aguardando Retirada'), ('Em Orçamento', 'Em Orçamento'), ('Entregue', 'Entregue ao Cliente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='devices',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices_technicals', to='technicals.technicals'),
        ),
    ]
