# Generated by Django 5.0.2 on 2024-03-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devices_repair_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
