# Generated by Django 5.0.2 on 2024-02-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicals',
            name='phone_number',
            field=models.CharField(default='Não Informado', max_length=20),
        ),
    ]
