# Generated by Django 5.0.2 on 2024-03-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicals', '0002_technicals_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicals',
            name='employee_position',
            field=models.CharField(choices=[('Atendente', 'Atendente'), ('Gerente', 'Gerente'), ('Técnico', 'Técnico')], default='Técnico', max_length=100),
        ),
    ]
