# Generated by Django 5.0.2 on 2024-03-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicals', '0003_technicals_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicals',
            name='employee_position',
            field=models.CharField(choices=[('Atendente', 'Atendente'), ('Gerente', 'Gerente'), ('Técnico', 'Técnico')], max_length=100),
        ),
    ]
